In [1]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
soup = BeautifulSoup(soup.text, "lxml")
soup.text

/tmp/ipykernel_4691/4235586189.py:3: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')

'\n\n\n\n\n\nCOVID - Coronavirus Statistics - Worldometer\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCoronavirus\nPopulation\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\nCOVID-19 Coronavirus Pandemic\nLast updated: May 05, 2023, 07:06 GMT\nWeekly Trends - Graphs - Countries - News\n\nCoronavirus Cases:\n\n687,576,650        \n\n\nview by country\n\nDeaths:\n\n6,869,692\n\n\n\nRecovered:\n\n660,014,861\n\n\n\n\n\n\n\n\n\n\n                    Active Cases\n                \n\n\n\n\n\n\n\n\n20,692,097\nCurrently Infected Patients\n\n\n20,652,902 (99.8%)\n\n                                    in Mild Condition\n\n39,195 (0.2%)\n                                    Serious or Critical\n\n\nShow Graph\n\n\n\n\nShow Statistics\n\n\n\n\n\n\n\n\n\n\n\n\n                Closed Cases\n            \n\n\n\n\n\n\n\n\n666,884,553\nCases which had an outcome:\n\n\n660,014,861\n                                (99%)\n\n                                Recovered / Discharged\n\n\n                                    6,869,692\n                                (1%)\n                                Deaths\n\n\nShow Graph\n\n\n\n\nShow Statistics\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        daily \n\n\n\n                    linear \n\n\n\n                    logarithmic \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        daily \n\n\n\n                    linear \n\n\n\n                    logarithmic \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe charts above are updated after the close of the day in GMT+0. See more graphs\n\n\n\n\xa0\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nReported Cases and Deaths by Country or Territory        \n\nNOTE: \nEffective February 1, 2023, the Coronavirus Tracker has switched from LIVE to Daily Updates. \n        As a number of major countries have now transitioned to weekly updates, there is no  need anymore for immediate updates   throughout the day as soon as a new report is released. On January 29, 2020, Worldometer started tracking the coronavirus, providing the most timely and accurate global statistics to all users and institutions around the world at a time when this was extremely challenging. We thank everyone who participated in this extraordinary collaborative effort.\nThe day is reset after midnight GMT+0. The list of countries and their regional classification is based on the United Nations Geoscheme. Sources are provided under "Latest News."  Learn more about Worldometer\'s COVID-19 data\n\n\n\n\nReport coronavirus cases\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nMAIN\nWEEKLY TRENDS\n\n\n\n\nNow\nYesterday\n2 Days Ago\n\n\n                Columns \n\n\n\n\n\n\n\nAll\nEurope\nNorth America\nAsia\nSouth America\nAfrica\nOceania\n\n\n\n\n\n\n\n\n\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\nNew Cases/1M pop\nNew Deaths/1M pop\nActive Cases/1M pop\n\n\n\n\n\n\nNorth America\n\n126,309,685\n\n1,630,352\n\n122,090,281\n+1,003\n2,589,052\n6,413\n\n\n\n\n\nNorth America\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAsia\n\n216,724,187\n+18,459\n1,544,873\n+6\n200,607,206\n+4,932\n14,572,108\n15,649\n\n\n\n\n\nAsia\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nEurope\n\n248,938,503\n\n2,053,808\n\n244,762,390\n+2,996\n2,122,305\n6,362\n\n\n\n\n\nEurope\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSouth America\n\n68,600,642\n\n1,354,635\n\n66,449,498\n\n796,509\n10,134\n\n\n\n\n\nSouth America\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nOceania\n\n14,182,986\n\n27,278\n\n14,020,441\n\n135,267\n89\n\n\n\n\n\nAustralia/Oceania\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAfrica\n\n12,819,926\n\n258,731\n\n12,084,339\n\n476,856\n548\n\n\n\n\n\nAfrica\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n721\n\n15\n\n706\n\n0\n0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWorld\n687,576,650\n+18,459\n6,869,692\n+6\n660,014,861\n+8,903\n20,692,097\n39,195\n88,210\n881.3\n\n\n\nAll\n\n\n\n\n\n\n\n\n\n\n\n\n1\nUSA\n106,762,797\n\n1,162,403                                \n\n104,699,401\n\n900,993\n1,247\n318,880\n3,472\n1,178,666,374\n3,520,453\n334,805,269 \nNorth America\n\n32880\n\n\n2,691\n\n\n2\nIndia\n44,960,678\n\n531,606                                \n\n44,392,828\n\n36,244\nN/A\n31,963\n378\n927,239,236\n659,191\n1,406,631,776 \nAsia\n\n312,6462\n\n\n26\n\n\n3\nFrance\n40,007,281\n\n166,645                                \n\n39,720,963\n\n119,673\n869\n610,011\n2,541\n271,490,188\n4,139,547\n65,584,518 \nEurope\n\n23940\n\n\n1,825\n\n\n4\nGermany\n38,409,620\n\n173,307                                \n\n38,204,800\n\n31,513\nN/A\n457,892\n2,066\n122,332,384\n1,458,359\n83,883,596 \nEurope\n\n24841\n\n\n376\n\n\n5\nBrazil\n37,487,971\n\n701,833                                \n\n36,249,161\n\n536,977\nN/A\n174,076\n3,259\n63,776,166\n296,146\n215,353,593 \nSouth America\n\n63073\n\n\n2,493\n\n\n6\nJapan\n33,766,957\n\n74,614                                \n\nN/A\nN/A\nN/A\n71\n268,878\n594\n100,342,320\n799,000\n125,584,838 \nAsia\n\n41,6831\n\n\n95,291\n\n\n7\nS. Korea\n31,251,203\n+18,459\n34,518                                \n+6\n30,959,576\n+4,939\n257,109\n141\n608,830\n672\n15,804,065\n307,892\n51,329,899 \nAsia\n\n21,4873\n360\n0.1\n5,009\n\n\n8\nItaly\n25,788,387\n\n189,738                                \n\n25,468,617\n\n130,032\n100\n427,932\n3,149\n271,449,155\n4,504,425\n60,262,770 \nEurope\n\n23180\n\n\n2,158\n\n\n9\nUK\n24,569,895\n\n223,396                                \n\n24,323,813\n+1,833\n22,686\nN/A\n358,696\n3,261\n522,526,476\n7,628,357\n68,497,907 \nEurope\n\n33070\n\n\n331\n\n\n10\nRussia\n22,866,342\n\n398,431                                \n\n22,273,109\n\n194,802\nN/A\n156,827\n2,733\n273,400,000\n1,875,095\n145,805,947 \nEurope\n\n63661\n\n\n1,336\n\n\n11\nTurkey\n17,232,066\n\n102,174                                \n\nN/A\nN/A\nN/A\n\n201,399\n1,194\n162,743,369\n1,902,052\n85,561,976 \nAsia\n\n58371\n\n\n4,024\n\n\n12\nSpain\n13,825,052\n\n120,715                                \n\n13,665,628\n\n38,709\n231\n295,918\n2,584\n471,036,328\n10,082,298\n46,719,142 \nEurope\n\n33870\n\n\n829\n\n\n13\nVietnam\n11,567,728\n\n43,195                                \n\n10,624,841\n\n899,692\n130\n116,901\n437\n85,826,548\n867,342\n98,953,541 \nAsia\n\n92,2911\n\n\n9,092\n\n\n14\nAustralia\n11,441,894\n\n20,272                                \n\n11,394,719\n\n26,903\n61\n438,912\n778\n78,835,048\n3,024,116\n26,068,792 \nAustralia/Oceania\n\n21,2860\n\n\n1,032\n\n\n15\nTaiwan\n10,239,998\n\n19,005                                \n\n10,220,993\n\n0\n\n428,656\n796\n30,742,304\n1,286,903\n23,888,595 \nAsia\n\n21,2571\n\n\n\n\n\n16\nArgentina\n10,044,957\n\n130,472                                \n\n9,914,485\n\n0\n363\n218,320\n2,836\n35,716,069\n776,264\n46,010,234 \nSouth America\n\n53531\n\n\n\n\n\n17\nNetherlands\n8,610,372\n\n22,992                                \n\n8,587,380\n+579\n0\n53\n500,270\n1,336\n25,984,435\n1,509,718\n17,211,447 \nEurope\n\n27491\n\n\n\n\n\n18\nIran\n7,607,744\n\n146,058                                \n\n7,342,490\n\n119,196\n407\n88,439\n1,698\n55,353,767\n643,478\n86,022,837 \nAsia\n\n115892\n\n\n1,386\n\n\n19\nMexico\n7,587,643\n\n333,913                                \n\n6,833,884\n\n419,846\nN/A\n57,673\n2,538\n19,930,737\n151,492\n131,562,772 \nNorth America\n\n173947\n\n\n3,191\n\n\n20\nIndonesia\n6,782,048\n\n161,384                                \n\n6,603,711\n\n16,953\nN/A\n24,297\n578\n114,158,919\n408,975\n279,134,505 \nAsia\n\n411,7302\n\n\n61\n\n\n21\nPoland\n6,514,251\n\n119,557                                \n\n5,335,940\n\n1,058,754\n648\n172,610\n3,168\n38,672,987\n1,024,727\n37,739,785 \nEurope\n\n63161\n\n\n28,054\n\n\n22\nColombia\n6,365,262\n\n142,722                                \n\n6,187,494\n\n35,046\n342\n123,567\n2,771\n36,951,507\n717,327\n51,512,762 \nSouth America\n\n83611\n\n\n680\n\n\n23\nAustria\n6,067,554\n\n22,405                                \n\n6,035,469\n\n9,680\n55\n669,212\n2,471\n211,273,524\n23,302,116\n9,066,710 \nEurope\n\n14050\n\n\n1,068\n\n\n24\nGreece\n6,018,544\n\n36,754                                \n\n5,960,580\n\n21,210\n115\n583,382\n3,563\n102,228,365\n9,909,078\n10,316,637 \nEurope\n\n22810\n\n\n2,056\n\n\n25\nPortugal\n5,581,619\n\n26,575                                \n\n5,550,008\n\n5,036\n61\n550,425\n2,621\n46,082,209\n4,544,341\n10,140,570 \nEurope\n\n23820\n\n\n497\n\n\n26\nUkraine\n5,529,459\n\n112,128                                \n\n5,389,891\n\n27,440\n\n128,020\n2,596\n32,603,805\n754,855\n43,192,122 \nEurope\n\n83851\n\n\n635\n\n\n27\nChile\n5,284,719\n\n64,497                                \n\n5,219,820\n\n402\n44\n274,528\n3,350\n49,432,422\n2,567,892\n19,250,195 \nSouth America\n\n42980\n\n\n21\n\n\n28\nMalaysia\n5,071,840\n\n37,020                                \n\n5,020,529\n\n14,291\n29\n152,853\n1,116\n68,347,420\n2,059,832\n33,181,072 \nAsia\n\n78960\n\n\n431\n\n\n29\nIsrael\n4,822,896\n\n12,500                                \n\n4,798,473\n\n11,923\n21\n517,145\n1,340\n41,373,364\n4,436,346\n9,326,000 \nAsia\n\n27460\n\n\n1,278\n\n\n30\nBelgium\n4,793,425\n\n34,237                                \n\n4,746,904\n+861\n12,284\n43\n410,808\n2,934\n37,018,657\n3,172,590\n11,668,278 \nEurope\n\n23410\n\n\n1,053\n\n\n31\nDPRK\n4,772,813\n\n74                                \n\n4,772,739\n\n0\n\n183,636\n3\n\n\n25,990,679 \nAsia\n\n5351,225\n\n\n\n\n\n32\nThailand\n4,732,301\n\n33,957                                \n\n4,692,636\n\n5,708\nN/A\n67,529\n485\n17,270,775\n246,450\n70,078,203 \nAsia\n\n152,0644\n\n\n81\n\n\n33\nCanada\n4,641,301\n\n52,247                                \n\n4,585,040\n+1,003\n4,014\n99\n120,904\n1,361\n66,343,123\n1,728,207\n38,388,419 \nNorth America\n\n87351\n\n\n105\n\n\n34\nCzechia\n4,640,543\n\n42,774                                \n\n4,595,388\n\n2,381\n10\n432,210\n3,984\n57,181,753\n5,325,780\n10,736,784 \nEurope\n\n22510\n\n\n222\n\n\n35\nPeru\n4,503,222\n\n220,196                                \n\n4,279,159\n\n3,867\n26\n133,689\n6,537\n38,548,796\n1,144,417\n33,684,208 \nSouth America\n\n71531\n\n\n115\n\n\n36\nSwitzerland\n4,402,438\n\n14,452                                \n\n4,383,180\n\n4,806\n39\n501,780\n1,647\n23,833,472\n2,716,487\n8,773,637 \nEurope\n\n26070\n\n\n548\n\n\n37\nPhilippines\n4,096,335\n\n66,444                                \n\n4,022,326\n\n7,565\n162\n36,409\n591\n35,037,470\n311,419\n112,508,994 \nAsia\n\n271,6933\n\n\n67\n\n\n38\nSouth Africa\n4,076,463\n\n102,595                                \n\n3,912,506\n\n61,362\n192\n67,095\n1,689\n26,795,090\n441,027\n60,756,135 \nAfrica\n\n155922\n\n\n1,010\n\n\n39\nRomania\n3,393,902\n\n68,089                                \n\n3,314,667\n\n11,146\n128\n178,332\n3,578\n27,242,332\n1,431,446\n19,031,335 \nEurope\n\n62801\n\n\n586\n\n\n40\nDenmark\n3,180,726\n\n8,572                                \n\n3,171,359\n\n795\n19\n545,116\n1,469\n129,268,444\n22,154,165\n5,834,950 \nEurope\n\n26810\n\n\n136\n\n\n41\nHong Kong\n2,892,450\n\n13,563                                \n\n2,871,114\n\n7,773\n28\n380,370\n1,784\n76,127,725\n10,011,143\n7,604,299 \nAsia\n\n35610\n\n\n1,022\n\n\n42\nSweden\n2,707,189\n\n24,141                                \n\n2,678,950\n\n4,098\n8\n264,918\n2,362\n19,500,873\n1,908,301\n10,218,971 \nEurope\n\n44231\n\n\n401\n\n\n43\nSerbia\n2,536,159\n\n18,022                                \n\n2,509,836\n\n8,301\n15\n293,095\n2,083\n12,806,989\n1,480,061\n8,653,016 \nEurope\n\n34801\n\n\n959\n\n\n44\nIraq\n2,465,545\n\n25,375                                \n\n2,439,497\n\n673\n21\n58,474\n602\n19,544,451\n463,523\n42,164,965 \nAsia\n\n171,6622\n\n\n16\n\n\n45\nSingapore\n2,340,779\n\n1,727                                \n\n2,149,583\n\n189,469\n2\n393,835\n291\n24,756,666\n4,165,302\n5,943,546 \nAsia\n\n33,4420\n\n\n31,878\n\n\n46\nNew Zealand\n2,324,094\n\n4,154                                \n\n2,310,320\n\n9,620\n\n474,479\n848\n7,768,604\n1,586,011\n4,898,203 \nAustralia/Oceania\n\n21,1791\n\n\n1,964\n\n\n47\nHungary\n2,201,355\n\n48,846                                \n\n2,148,647\n\n3,862\n13\n229,158\n5,085\n11,394,556\n1,186,160\n9,606,259 \nEurope\n\n41971\n\n\n402\n\n\n48\nBangladesh\n2,038,250\n\n29,446                                \n\n1,998,448\n\n10,356\nN/A\n12,141\n175\n15,254,399\n90,862\n167,885,689 \nAsia\n\n825,70111\n\n\n62\n\n\n49\nSlovakia\n1,866,470\n\n21,167                                \n\n1,845,061\n+33\n242\n18\n341,832\n3,877\n7,427,231\n1,360,251\n5,460,193 \nEurope\n\n32581\n\n\n44\n\n\n50\nGeorgia\n1,840,187\n\n17,059                                \n\n1,776,548\n\n46,580\n\n463,671\n4,298\n16,920,079\n4,263,340\n3,968,738 \nAsia\n\n22330\n\n\n11,737\n\n\n51\nJordan\n1,746,997\n\n14,122                                \n\n1,731,007\n\n1,868\n59\n169,597\n1,371\n17,201,885\n1,669,945\n10,300,869 \nAsia\n\n67291\n\n\n181\n\n\n52\nIreland\n1,710,625\n\n8,866                                \n\n1,699,569\n\n2,190\n19\n340,748\n1,766\n13,083,449\n2,606,161\n5,020,199 \nEurope\n\n35660\n\n\n436\n\n\n53\nPakistan\n1,580,801\n\n30,658                                \n\n1,538,689\n\n11,454\n8\n6,888\n134\n30,571,377\n133,215\n229,488,994 \nAsia\n\n1457,4858\n\n\n50\n\n\n54\nNorway\n1,483,454\n\n5,213                                \n\n1,477,213\n\n1,028\n20\n269,162\n946\n11,002,430\n1,996,315\n5,511,370 \nEurope\n\n41,0571\n\n\n187\n\n\n55\nFinland\n1,475,378\n\n9,373                                \n\n1,459,986\n\n6,019\n21\n265,597\n1,687\n12,090,288\n2,176,485\n5,554,960 \nEurope\n\n45930\n\n\n1,084\n\n\n56\nKazakhstan\n1,411,768\n\n13,848                                \n\n1,383,020\n\n14,900\n24\n73,510\n721\n11,575,012\n602,707\n19,205,043 \nAsia\n\n141,3872\n\n\n776\n\n\n57\nSlovenia\n1,343,364\n\n7,100                                \n\n1,328,006\n\n8,258\n8\n646,459\n3,417\n2,847,701\n1,370,382\n2,078,034 \nEurope\n\n22931\n\n\n3,974\n\n\n58\nLithuania\n1,318,786\n\n9,669                                \n\n1,307,212\n\n1,905\n2\n495,466\n3,633\n10,439,469\n3,922,094\n2,661,708 \nEurope\n\n22750\n\n\n716\n\n\n59\nBulgaria\n1,305,030\n\n38,339                                \n\n1,264,067\n\n2,624\n30\n190,666\n5,601\n11,190,426\n1,634,928\n6,844,597 \nEurope\n\n51791\n\n\n383\n\n\n60\nMorocco\n1,273,463\n\n16,297                                \n\n1,256,151\n\n1,015\n3\n33,714\n431\n13,001,033\n344,191\n37,772,756 \nAfrica\n\n302,3183\n\n\n27\n\n\n61\nCroatia\n1,272,886\n\n18,180                                \n\n1,253,558\n\n1,148\n6\n313,574\n4,479\n5,582,393\n1,375,215\n4,059,286 \nEurope\n\n32231\n\n\n283\n\n\n62\nGuatemala\n1,248,823\n\n20,196                                \n\n1,227,381\n\n1,246\n5\n67,199\n1,087\n7,235,362\n389,332\n18,584,039 \nNorth America\n\n159203\n\n\n67\n\n\n63\nLebanon\n1,236,971\n\n10,904                                \n\n1,087,587\n\n138,480\n74\n185,041\n1,631\n4,795,578\n717,380\n6,684,849 \nAsia\n\n56131\n\n\n20,716\n\n\n64\nCosta Rica\n1,228,659\n\n9,351                                \n\n860,711\n\n358,597\n52\n237,085\n1,804\n4,659,757\n899,158\n5,182,354 \nNorth America\n\n45541\n\n\n69,196\n\n\n65\nBolivia\n1,197,458\n\n22,377                                \n\n1,166,413\n\n8,668\n220\n99,849\n1,866\n2,705,422\n225,590\n11,992,656 \nSouth America\n\n105364\n\n\n723\n\n\n66\nTunisia\n1,152,877\n\n29,398                                \n\nN/A\nN/A\nN/A\n44\n95,701\n2,440\n5,010,521\n415,926\n12,046,656 \nAfrica\n\n104102\n\n\n1,119\n\n\n67\nCuba\n1,113,374\n\n8,530                                \n\n1,104,696\n\n148\n2\n98,479\n754\n14,345,279\n1,268,859\n11,305,652 \nNorth America\n\n101,3251\n\n\n13\n\n\n68\nUAE\n1,063,002\n\n2,349                                \n\n1,046,765\n\n13,888\n\n105,438\n233\n200,369,120\n19,874,369\n10,081,785 \nAsia\n\n94,2920\n\n\n1,378\n\n\n69\nEcuador\n1,061,100\n\n36,019                                \n\n1,023,510\n\n1,571\n759\n58,581\n1,989\n3,082,403\n170,173\n18,113,361 \nSouth America\n\n175036\n\n\n87\n\n\n70\nUruguay\n1,037,893\n\n7,625                                \n\n1,029,835\n\n433\n18\n296,879\n2,181\n6,114,822\n1,749,083\n3,496,016 \nSouth America\n\n34581\n\n\n124\n\n\n71\nPanama\n1,037,324\n\n8,621                                \n\n1,028,182\n\n521\n16\n233,266\n1,939\n7,660,443\n1,722,623\n4,446,964 \nNorth America\n\n45161\n\n\n117\n\n\n72\nMongolia\n1,007,993\n\n2,179                                \n\n1,005,787\n\n27\n192\n298,392\n645\n4,030,048\n1,193,000\n3,378,078 \nAsia\n\n31,5501\n\n\n8\n\n\n73\nNepal\n1,003,064\n\n12,031                                \n\n990,831\n\n202\n\n33,186\n398\n6,036,615\n199,719\n30,225,582 \nAsia\n\n302,5125\n\n\n7\n\n\n74\nBelarus\n994,037\n\n7,118                                \n\n985,592\n\n1,327\n\n105,381\n755\n13,646,641\n1,446,722\n9,432,800 \nEurope\n\n91,3251\n\n\n141\n\n\n75\nLatvia\n977,697\n\n6,325                                \n\n971,095\n\n277\n13\n528,817\n3,421\n7,874,100\n4,258,948\n1,848,837 \nEurope\n\n22920\n\n\n150\n\n\n76\nSaudi Arabia\n841,348\n\n9,646                                \n\n827,696\n\n4,006\n65\n23,472\n269\n45,476,472\n1,268,701\n35,844,909 \nAsia\n\n433,7161\n\n\n112\n\n\n77\nAzerbaijan\n831,460\n\n10,250                                \n\n820,953\n\n257\n\n80,723\n995\n7,593,644\n737,232\n10,300,205 \nAsia\n\n121,0051\n\n\n25\n\n\n78\nParaguay\n809,731\n\n19,916                                \n\nN/A\nN/A\nN/A\n7\n110,833\n2,726\n2,657,506\n363,751\n7,305,843 \nSouth America\n\n93673\n\n\n12,524\n\n\n79\nBahrain\n720,424\n\n1,562                                \n\n718,310\n\n552\n1\n403,829\n876\n10,833,573\n6,072,688\n1,783,983 \nAsia\n\n21,1420\n\n\n309\n\n\n80\nSri Lanka\n672,188\n\n16,844                                \n\n655,320\n\n24\n\n31,155\n781\n6,486,117\n300,619\n21,575,842 \nAsia\n\n321,2813\n\n\n1\n\n\n81\nKuwait\n665,741\n\n2,570                                \n\n660,237\n\n2,934\n\n151,984\n587\n8,455,743\n1,930,391\n4,380,326 \nAsia\n\n71,7041\n\n\n670\n\n\n82\nDominican Republic\n661,045\n\n4,384                                \n\n644,785\n\n11,876\n4\n59,789\n397\n3,740,928\n338,350\n11,056,370 \nNorth America\n\n172,5223\n\n\n1,074\n\n\n83\nCyprus\n658,450\n\n1,354                                \n\n655,550\n\n1,546\n60\n538,219\n1,107\n9,640,118\n7,879,860\n1,223,387 \nAsia\n\n29040\n\n\n1,264\n\n\n84\nMyanmar\n635,452\n\n19,492                                \n\n614,998\n\n962\n\n11,506\n353\n10,407,809\n188,455\n55,227,143 \nAsia\n\n872,8335\n\n\n17\n\n\n85\nPalestine\n621,008\n\n5,404                                \n\n615,445\n\n159\n17\n116,173\n1,011\n3,078,533\n575,907\n5,345,541 \nAsia\n\n99892\n\n\n30\n\n\n86\nMoldova\n620,419\n\n12,113                                \n\n504,142\n\n104,164\n49\n154,596\n3,018\n3,216,305\n801,437\n4,013,171 \nEurope\n\n63311\n\n\n25,956\n\n\n87\nEstonia\n618,200\n\n3,001                                \n\n524,990\n\n90,209\n3\n467,657\n2,270\n3,706,919\n2,804,214\n1,321,910 \nEurope\n\n24400\n\n\n68,241\n\n\n88\nVenezuela\n552,695\n\n5,856                                \n\n546,537\n\n302\n31\n18,885\n200\n3,359,014\n114,771\n29,266,991 \nSouth America\n\n534,9989\n\n\n10\n\n\n89\nEgypt\n515,970\n\n24,613                                \n\n442,182\n\n49,175\n122\n4,860\n232\n3,693,367\n34,792\n106,156,692 \nAfrica\n\n2064,31329\n\n\n463\n\n\n90\nQatar\n509,440\n\n690                                \n\n507,534\n\n1,216\n32\n170,958\n232\n4,065,369\n1,364,257\n2,979,915 \nAsia\n\n64,3191\n\n\n408\n\n\n91\nLibya\n507,252\n\n6,437                                \n\n500,813\n\n2\n\n72,045\n914\n2,483,848\n352,782\n7,040,745 \nAfrica\n\n141,0943\n\n\n0.3\n\n\n92\nEthiopia\n500,847\n\n7,574  

In [2]:
table_code = soup.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>126,309,685</td>
<td></td>
<td>1,630,352</td>
<td></td>
<td>122,090,281</td>
<td>+1,003</td>
<td>2,589,052</td>
<td>6,413</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>216,724,187</td>
<td>+18,459</td>
<td>1,544,873</td>
<td>+6</td>
<td>200,607,206</td>
<td>+4,932</td>
<td>14,572,108</td>
<td>15,649</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>248,938,503</td>
<td></td>
<td>2,053,808</td>
<td></td>
<td>244,762,390</td>
<td>+2,996</td>
<td>2,122,305</td>
<td>6,362</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,600,642</td>
<td></td>
<td>1,354,635</td>
<td></td>
<td>66,449,498</td>
<td></td>
<td>796,509</td>
<td>10,134</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,182,986</td>
<td></td>
<td>27,278</td>
<td></td>
<td>14,020,441</td>
<td></td>
<td>135,267</td>
<td>89</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,819,926</td>
<td></td>
<td>258,731</td>
<td></td>
<td>12,084,339</td>
<td></td>
<td>476,856</td>
<td>548</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>687,576,650</td>
<td>+18,459</td>
<td>6,869,692</td>
<td>+6</td>
<td>660,014,861</td>
<td>+8,903</td>
<td>20,692,097</td>
<td>39,195</td>
<td>88,210</td>
<td>881.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">106,762,797</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,162,403                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">104,699,401</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">900,993</td>
<td style="font-weight: bold; text-align:right">1,247</td>
<td style="font-weight: bold; text-align:right">318,880</td>
<td style="font-weight: bold; text-align:right">3,472</td>
<td style="font-weight: bold; text-align:right">1,178,666,374</td>
<td style="font-weight: bold; text-align:right">3,520,453</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>288</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,691</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,960,678</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">531,606                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,392,828</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">36,244</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,963</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">927,239,236</td>
<td style="font-weight: bold; text-align:right">659,191</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,646</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">26</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,007,281</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">166,645                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,720,963</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">119,673</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">610,011</td>
<td style="font-weight: bold; text-align:right">2,541</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>394</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,825</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,409,620</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">173,307                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,204,800</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">31,513</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">457,892</td>
<td style="font-weight: bold; text-align:right">2,066</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>484</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">376</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,487,971</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">701,833                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">536,977</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">174,076</td>
<td style="font-weight: bold; text-align:right">3,259</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>307</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,493</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,766,957</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,614                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">71</td>
<td style="font-weight: bold; text-align:right">268,878</td>
<td style="font-weight: bold; text-align:right">594</td>
<td style="font-weight: bold; text-align:right">100,342,320</td>
<td style="font-weight: bold; text-align:right">799,000</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,683</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,291</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">31,251,203</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,459</td>
<td style="font-weight: bold; text-align:right;">34,518                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+6</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,959,576</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,939</td>
<td style="text-align:right;font-weight:bold;">257,109</td>
<td style="font-weight: bold; text-align:right">141</td>
<td style="font-weight: bold; text-align:right">608,830</td>
<td style="font-weight: bold; text-align:right">672</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,487</td><td>3</td>
<td style="font-weight: bold; text-align:right">360</td>
<td style="font-weight: bold; text-align:right">0.1</td>
<td style="font-weight: bold; text-align:right">5,009</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,788,387</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">189,738                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,468,617</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">130,032</td>
<td style="font-weight: bold; text-align:right">100</td>
<td style="font-weight: bold; text-align:right">427,932</td>
<td style="font-weight: bold; text-align:right">3,149</td>
<td style="font-weight: bold; text-align:right">271,449,155</td>
<td style="font-weight: bold; text-align:right">4,504,425</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>318</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,158</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,569,895</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">223,396                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,323,813</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,833</td>
<td style="text-align:right;font-weight:bold;">22,686</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">358,696</td>
<td style="font-weight: bold; text-align:right">3,261</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>307</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">331</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,866,342</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">398,431                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,273,109</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">194,802</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">156,827</td>
<td style="font-weight: bold; text-align:right">2,733</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>366</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,336</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>

In [3]:
table_code.find_all('tr')

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>126,309,685</td>
 <td></td>
 <td>1,630,352</td>
 <td></td>
 <td>122,090,281</td>
 <td>+1,003</td>
 <td>2,589,052</td>
 <td>6,413</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>216,724,187</td>
 <td>+18,459</td>
 <td>1,544,873</td>
 <td>+6</td>
 <td>200,607,206</td>
 <td>+4,932</td>
 <td>14,572,108</td>
 <td>15,649</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>248,938,503</td>
 <td></td>
 <td>2,053,808</td>
 <td></td>
 <td>244,762,390</td>
 <td>+2,996</td>
 <td>2,122,305</td>
 <td>6,362</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>68,600,642</td>
 <td></td>
 <td>1,354,635</td>
 <td></td>
 <td>66,449,498</td>
 <td></td>
 <td>796,509</td>
 <td>10,134</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,182,986</td>
 <td></td>
 <td>27,278</td>
 <td></td>
 <td>14,020,441</td>
 <td></td>
 <td>135,267</td>
 <td>89</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,819,926</td>
 <td></td>
 <td>258,731</td>
 <td></td>
 <td>12,084,339</td>
 <td></td>
 <td>476,856</td>
 <td>548</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>687,576,650</td>
 <td>+18,459</td>
 <td>6,869,692</td>
 <td>+6</td>
 <td>660,014,861</td>
 <td>+8,903</td>
 <td>20,692,097</td>
 <td>39,195</td>
 <td>88,210</td>
 <td>881.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">106,762,797</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,162,403                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">104,699,401</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">900,993</td>
 <td style="font-weight: bold; text-align:right">1,247</td>
 <td style="font-weight: bold; text-align:right">318,880</td>
 <td style="font-weight: bold; text-align:right">3,472</td>
 <td style="font-weight: bold; text-align:right">1,178,666,374</td>
 <td style="font-weight: bold; text-align:right">3,520,453</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>288</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,691</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,960,678</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">531,606                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,392,828</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">36,244</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">31,963</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">927,239,236</td>
 <td style="font-weight: bold; text-align:right">659,191</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,646</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">26</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,007,281</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">166,645                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,720,963</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">119,673</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">610,011</td>
 <td style="font-weight: bold; text-align:right">2,541</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>394</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,825</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,409,620</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">173,307                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,204,800</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">31,513</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">457,892</td>
 <td style="font-weight: bold; text-align:right">2,066</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>484</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">376</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">37,487,971</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">701,833                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">536,977</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">174,076</td>
 <td style="font-weight: bold; text-align:right">3,259</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>307</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,493</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,766,957</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,614                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">71</td>
 <td style="font-weight: bold; text-align:right">268,878</td>
 <td style="font-weight: bold; text-align:right">594</td>
 <td style="font-weight: bold; text-align:right">100,342,320</td>
 <td style="font-weight: bold; text-align:right">799,000</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,683</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,291</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">31,251,203</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,459</td>
 <td style="font-weight: bold; text-align:right;">34,518                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+6</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,959,576</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,939</td>
 <td style="text-align:right;font-weight:bold;">257,109</td>
 <td style="font-weight: bold; text-align:right">141</td>
 <td style="font-weight: bold; text-align:right">608,830</td>
 <td style="font-weight: bold; text-align:right">672</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,487</td><td>3</td>
 <td style="font-weight: bold; text-align:right">360</td>
 <td style="font-weight: bold; text-align:right">0.1</td>
 <td style="font-weight: bold; text-align:right">5,009</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,788,387</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">189,738                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,468,617</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">130,032</td>
 <td style="font-weight: bold; text-align:right">100</td>
 <td style="font-weight: bold; text-align:right">427,932</td>
 <td style="font-weight: bold; text-align:right">3,149</td>
 <td style="font-weight: bold; text-align:right">271,449,155</td>
 <td style="font-weight: bold; text-align:right">4,504,425</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>318</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,158</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,569,895</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">223,396                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,323,813</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,833</td>
 <td style="text-align:right;font-weight:bold;">22,686</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">358,696</td>
 <td style="font-weight: bold; text-align:right">3,261</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>307</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">331</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">22,866,342</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">398,431                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,273,109</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">194,802</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">156,827</td>
 <td style="font-weight: bold; text-align:right">2,733</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->

In [14]:
final_data = []
tr_tags = table_code.find_all('tr')
for i in tr_tags:
    x = i.text.split('\n')
    if x[1] != "":
        final_data.append(x[1:-1])
# final_data
# tr_tags[0].text

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop'],
 ['1',
  'USA',
  '106,762,797',
  '',
  '1,162,403                                ',
  '',
  '104,699,401',
  '',
  '900,993',
  '1,247',
  '318,880',
  '3,472',
  '1,178,666,374',
  '3,520,453',
  '334,805,269 ',
  'North America',
  '',
  '32880',
  '',
  '',
  '2,691'],
 ['2',
  'India',
  '44,960,678',
  '',
  '531,606                                ',
  '',
  '44,392,828',
  '',
  '36,244',
  'N/A',
  '31,963',
  '378',
  '927,239,236',
  '659,191',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6462',
  '',
  '',
  '26'],
 ['3',
  'France',
  '40,007,281',
  '',
  '166,645                                ',
  '',
  '39,720,963',
  '',
  '119,673',
  '869',
  '610,011',
  '2,541',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23940',
  '',
  '',
  '1,825'],
 ['4',
  'Germany',
  '38,409,620',
  '',
  '173,307                                ',
  '',
  '38,204,800',
  '',
  '31,513',
  'N/A',
  '457,892',
  '2,066',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24841',
  '',
  '',
  '376'],
 ['5',
  'Brazil',
  '37,487,971',
  '',
  '701,833                                ',
  '',
  '36,249,161',
  '',
  '536,977',
  'N/A',
  '174,076',
  '3,259',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63073',
  '',
  '',
  '2,493'],
 ['6',
  'Japan',
  '33,766,957',
  '',
  '74,614                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '71',
  '268,878',
  '594',
  '100,342,320',
  '799,000',
  '125,584,838 ',
  'Asia',
  '',
  '41,6831',
  '',
  '',
  '95,291'],
 ['7',
  'S. Korea',
  '31,251,203',
  '+18,459',
  '34,518                                ',
  '+6',
  '30,959,576',
  '+4,939',
  '257,109',
  '141',
  '608,830',
  '672',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,4873',
  '360',
  '0.1',
  '5,009'],
 ['8',
  'Italy',
  '25,788,387',
  '',
  '189,738                                ',
  '',
  '25,468,617',
  '',
  '130,032',
  '100',
  '427,932',
  '3,149',
  '271,449,155',
  '4,504,425',
  '60,262,770 ',
  'Europe',
  '',
  '23180',
  '',
  '',
  '2,158'],
 ['9',
  'UK',
  '24,569,895',
  '',
  '223,396                                ',
  '',
  '24,323,813',
  '+1,833',
  '22,686',
  'N/A',
  '358,696',
  '3,261',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33070',
  '',
  '',
  '331'],
 ['10',
  'Russia',
  '22,866,342',
  '',
  '398,431                                ',
  '',
  '22,273,109',
  '',
  '194,802',
  'N/A',
  '156,827',
  '2,733',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63661',
  '',
  '',
  '1,336'],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024'],
 ['12',
  'Spain',
  '13,825,052',
  '',
  '120,715                                ',
  '',
  '13,665,628',
  '',
  '38,709',
  '231',
  '295,918',
  '2,584',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33870',
  '',
  '',
  '829'],
 ['13',
  'Vietnam',
  '11,567,728',
  '',
  '43,195                                ',
  '',
  '10,624,841',
  '',
  '899,692',
  '130',
  '116,901',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2911',
  '',
  '',
  '9,092'],
 ['14',
  'Australia',
  '11,441,894',
  '',
  '20,272                                ',
  '',
  '11,394,719',
  '',
  '26,903',
  '61',
  '438,912',
  '778',
  '78,835,048',
  '3,024,116',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,2860',
  '',
  '',
  '1,032'],
 ['15',
  'Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993',
  '',
  '0',
  '',
  '428,656',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  ''],
 ['16',
  'Argentina',
  '10,044,957',
  '',
  '130,472                                ',
  '',
  '9,914,485',
  '',
  '0',
  '363',
  '218,320',
  '2,836',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  ''],
 ['17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,587,380',
  '+579',
  '0',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  ''],
 ['18',
  'Iran',
  '7,607,744',
  '',
  '146,058                                ',
  '',
  '7,342,490',
  '',
  '119,196',
  '407',
  '88,439',
  '1,698',
  '55,353,767',
  '643,478',
  '86,022,837 ',
  'Asia',
  '',
  '115892',
  '',
  '',
  '1,386'],
 ['19',
  'Mexico',
  '7,587,643',
  '',
  '333,913                                ',
  '',
  '6,833,884',
  '',
  '419,846',
  'N/A',
  '57,673',
  '2,538',
  '19,930,737',
  '151,492',
  '131,562,772 ',
  'North America',
  '',
  '173947',
  '',
  '',
  '3,191'],
 ['20',
  'Indonesia',
  '6,782,048',
  '',
  '161,384                                ',
  '',
  '6,603,711',
  '',
  '16,953',
  'N/A',
  '24,297',
  '578',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7302',
  '',
  '',
  '61'],
 ['21',
  'Poland',
  '6,514,251',
  '',
  '119,557                                ',
  '',
  '5,335,940',
  '',
  '1,058,754',
  '648',
  '172,610',
  '3,168',
  '38,672,987',
  '1,024,727',
  '37,739,785 ',
  'Europe',
  '',
  '63161',
  '',
  '',
  '28,054'],
 ['22',
  'Colombia',
  '6,365,262',
  '',
  '142,722                                ',
  '',
  '6,187,494',
  '',
  '35,046',
  '342',
  '123,567',
  '2,771',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83611',
  '',
  '',
  '680'],
 ['23',
  'Austria',
  '6,067,554',
  '',
  '22,405                                ',
  '',
  '6,035,469',
  '',
  '9,680',
  '55',
  '669,212',
  '2,471',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14050',
  '',
  '',
  '1,068'],
 ['24',
  'Greece',
  '6,018,544',
  '',
  '36,754                                ',
  '',
  '5,960,580',
  '',
  '21,210',
  '115',
  '583,382',
  '3,563',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22810',
  '',
  '',
  '2,056'],
 ['25',
  'Portugal',
  '5,581,619',
  '',
  '26,575                                ',
  '',
  '5,550,008',
  '',
  '5,036',
  '61',
  '550,425',
  '2,621',
  '46,082,209',
  '4,544,341',
  '10,140,570 ',
  'Europe',
  '',
  '23820',
  '',
  '',
  '497'],
 ['26',
  'Ukraine',
  '5,529,459',
  '',
  '112,128                                ',
  '',
  '5,389,891',
  '',
  '27,440',
  '',
  '128,020',
  '2,596',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83851',
  '',
  '',
  '635'],
 ['27',
  'Chile',
  '5,284,719',
  '',
  '64,497                                ',
  '',
  '5,219,820',
  '',
  '402',
  '44',
  '274,528',
  '3,350',
  '49,432,422',
  '2,567,892',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '',
  '',
  '21'],
 ['28',
  'Malaysia',
  '5,071,840',
  '',
  '37,020                                ',
  '',
  '5,020,529',
  '',
  '14,291',
  '29',
  '152,853',
  '1,116',
  '68,347,420',
  '2,059,832',
  '33,181,072 ',
  'Asia',
  '',
  '78960',
  '',
  '',
  '431'],
 ['29',
  'Israel',
  '4,822,896',
  '',
  '12,500                                ',
  '',
  '4,798,473',
  '',
  '11,923',
  '21',
  '517,145',
  '1,340',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27460',
  '',
  '',
  '1,278'],
 ['30',
  'Belgium',
  '4,793,425',
  '',
  '34,237                                ',
  '',
  '4,746,904',
  '+861',
  '12,284',
  '43',
  '410,808',
  '2,934',
  '37,018,657',
  '3,172,590',
  '11,668,278 ',
  'Europe',
  '',
  '23410',
  '',
  '',
  '1,053'],
 ['31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  ''],
 ['32',
  'Thailand',
  '4,732,301',
  '',
  '33,957                                ',
  '',
  '4,692,636',
  '',
  '5,708',
  'N/A',
  '67,529',
  '485',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0644',
  '',
  '',
  '81'],
 ['33',
  'Canada',
  '4,641,301',
  '',
  '52,247                                ',
  '',
  '4,585,040',
  '+1,003',
  '4,014',
  '99',
  '120,904',
  '1,361',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '87351',
  '',
  '',
  '105'],
 ['34',
  'Czechia',
  '4,640,543',
  '',
  '42,774                                ',
  '',
  '4,595,388',
  '',
  '2,381',
  '10',
  '432,210',
  '3,984',
  '57,181,753',
  '5,325,780',
  '10,736,784 ',
  'Europe',
  '',
  '22510',
  '',
  '',
  '222'],
 ['35',
  'Peru',
  '4,503,222',
  '',
  '220,196                                ',
  '',
  '4,279,159',
  '',
  '3,867',
  '26',
  '133,689',
  '6,537',
  '38,548,796',
  '1,144,417',
  '33,684,208 ',
  'South America',
  '',
  '71531',
  '',
  '',
  '115'],
 ['36',
  'Switzerland',
  '4,402,438',
  '',
  '14,452                                ',
  '',
  '4,383,180',
  '',
  '4,806',
  '39',
  '501,780',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '548'],
 ['37',
  'Philippines',
  '4,096,335',
  '',
  '66,444                                ',
  '',
  '4,022,326',
  '',
  '7,565',
  '162',
  '36,409',
  '591',
  '35,037,470',
  '311,419',
  '112,508,994 ',
  'Asia',
  '',
  '271,6933',
  '',
  '',
  '67'],
 ['38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010'],
 ['39',
  'Romania',
  '3,393,902',
  '',
  '68,089                                ',
  '',
  '3,314,667',
  '',
  '11,146',
  '128',
  '178,332',
  '3,578',
  '27,242,332',
  '1,431,446',
  '19,031,335 ',
  'Europe',
  '',
  '62801',
  '',
  '',
  '586'],
 ['40',
  'Denmark',
  '3,180,726',
  '',
  '8,572                                ',
  '',
  '3,171,359',
  '',
  '795',
  '19',
  '545,116',
  '1,469',
  '129,268,444',
  '22,154,165',
  '5,834,950 ',
  'Europe',
  '',
  '26810',
  '',
  '',
  '136'],
 ['41',
  'Hong Kong',
  '2,892,450',
  '',
  '13,563                                ',
  '',
  '2,871,114',
  '',
  '7,773',
  '28',
  '380,370',
  '1,784',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35610',
  '',
  '',
  '1,022'],
 ['42',
  'Sweden',
  '2,707,189',
  '',
  '24,141                                ',
  '',
  '2,678,950',
  '',
  '4,098',
  '8',
  '264,918',
  '2,362',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '44231',
  '',
  '',
  '401'],
 ['43',
  'Serbia',
  '2,536,159',
  '',
  '18,022                                ',
  '',
  '2,509,836',
  '',
  '8,301',
  '15',
  '293,095',
  '2,083',
  '12,806,989',
  '1,480,061',
  '8,653,016 ',
  'Europe',
  '',
  '34801',
  '',
  '',
  '959'],
 ['44',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16'],
 ['45',
  'Singapore',
  '2,340,779',
  '',
  '1,727                                ',
  '',
  '2,149,583',
  '',
  '189,469',
  '2',
  '393,835',
  '291',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '33,4420',
  '',
  '',
  '31,878'],
 ['46',
  'New Zealand',
  '2,324,094',
  '',
  '4,154                                ',
  '',
  '2,310,320',
  '',
  '9,620',
  '',
  '474,479',
  '848',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,1791',
  '',
  '',
  '1,964'],
 ['47',
  'Hungary',
  '2,201,355',
  '',
  '48,846                                ',
  '',
  '2,148,647',
  '',
  '3,862',
  '13',
  '229,158',
  '5,085',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41971',
  '',
  '',
  '402'],
 ['48',
  'Bangladesh',
  '2,038,250',
  '',
  '29,446                                ',
  '',
  '1,998,448',
  '',
  '10,356',
  'N/A',
  '12,141',
  '175',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,70111',
  '',
  '',
  '62'],
 ['49',
  'Slovakia',
  '1,866,470',
  '',
  '21,167                                ',
  '',
  '1,845,061',
  '+33',
  '242',
  '18',
  '341,832',
  '3,877',
  '7,427,231',
  '1,360,251',
  '5,460,193 ',
  'Europe',
  '',
  '32581',
  '',
  '',
  '44'],
 ['50',
  'Georgia',
  '1,840,187',
  '',
  '17,059                                ',
  '',
  '1,776,548',
  '',
  '46,580',
  '',
  '463,671',
  '4,298',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22330',
  '',
  '',
  '11,737'],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181'],
 ['52',
  'Ireland',
  '1,710,625',
  '',
  '8,866                                ',
  '',
  '1,699,569',
  '',
  '2,190',
  '19',
  '340,748',
  '1,766',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35660',
  '',
  '',
  '436'],
 ['53',
  'Pakistan',
  '1,580,801',
  '',
  '30,658                                ',
  '',
  '1,538,689',
  '',
  '11,454',
  '8',
  '6,888',
  '134',
  '30,571,377',
  '133,215',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4858',
  '',
  '',
  '50'],
 ['54',
  'Norway',
  '1,483,454',
  '',
  '5,213                                ',
  '',
  '1,477,213',
  '',
  '1,028',
  '20',
  '269,162',
  '946',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,0571',
  '',
  '',
  '187'],
 ['55',
  'Finland',
  '1,475,378',
  '',
  '9,373                                ',
  '',
  '1,459,986',
  '',
  '6,019',
  '21',
  '265,597',
  '1,687',
  '12,090,288',
  '2,176,485',
  '5,554,960 ',
  'Europe',
  '',
  '45930',
  '',
  '',
  '1,084'],
 ['56',
  'Kazakhstan',
  '1,411,768',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,900',
  '24',
  '73,510',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '776'],
 ['57',
  'Slovenia',
  '1,343,364',
  '',
  '7,100                                ',
  '',
  '1,328,006',
  '',
  '8,258',
  '8',
  '646,459',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '',
  '',
  '3,974'],
 ['58',
  'Lithuania',
  '1,318,786',
  '',
  '9,669                                ',
  '',
  '1,307,212',
  '',
  '1,905',
  '2',
  '495,466',
  '3,633',
  '10,439,469',
  '3,922,094',
  '2,661,708 ',
  'Europe',
  '',
  '22750',
  '',
  '',
  '716'],
 ['59',
  'Bulgaria',
  '1,305,030',
  '',
  '38,339                                ',
  '',
  '1,264,067',
  '',
  '2,624',
  '30',
  '190,666',
  '5,601',
  '11,190,426',
  '1,634,928',
  '6,844,597 ',
  'Europe',
  '',
  '51791',
  '',
  '',
  '383'],
 ['60',
  'Morocco',
  '1,273,463',
  '',
  '16,297                                ',
  '',
  '1,256,151',
  '',
  '1,015',
  '3',
  '33,714',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '27'],
 ['61',
  'Croatia',
  '1,272,886',
  '',
  '18,180                                ',
  '',
  '1,253,558',
  '',
  '1,148',
  '6',
  '313,574',
  '4,479',
  '5,582,393',
  '1,375,215',
  '4,059,286 ',
  'Europe',
  '',
  '32231',
  '',
  '',
  '283'],
 ['62',
  'Guatemala',
  '1,248,823',
  '',
  '20,196                                ',
  '',
  '1,227,381',
  '',
  '1,246',
  '5',
  '67,199',
  '1,087',
  '7,235,362',
  '389,332',
  '18,584,039 ',
  'North America',
  '',
  '159203',
  '',
  '',
  '67'],
 ['63',
  'Lebanon',
  '1,236,971',
  '',
  '10,904                                ',
  '',
  '1,087,587',
  '',
  '138,480',
  '74',
  '185,041',
  '1,631',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56131',
  '',
  '',
  '20,716'],
 ['64',
  'Costa Rica',
  '1,228,659',
  '',
  '9,351                                ',
  '',
  '860,711',
  '',
  '358,597',
  '52',
  '237,085',
  '1,804',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45541',
  '',
  '',
  '69,196'],
 ['65',
  'Bolivia',
  '1,197,458',
  '',
  '22,377                                ',
  '',
  '1,166,413',
  '',
  '8,668',
  '220',
  '99,849',
  '1,866',
  '2,705,422',
  '225,590',
  '11,992,656 ',
  'South America',
  '',
  '105364',
  '',
  '',
  '723'],
 ['66',
  'Tunisia',
  '1,152,877',
  '',
  '29,398                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,701',
  '2,440',
  '5,010,521',
  '415,926',
  '12,046,656 ',
  'Africa',
  '',
  '104102',
  '',
  '',
  '1,119'],
 ['67',
  'Cuba',
  '1,113,374',
  '',
  '8,530                                ',
  '',
  '1,104,696',
  '',
  '148',
  '2',
  '98,479',
  '754',
  '14,345,279',
  '1,268,859',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '',
  '',
  '13'],
 ['68',
  'UAE',
  '1,063,002',
  '',
  '2,349                                ',
  '',
  '1,046,765',
  '',
  '13,888',
  '',
  '105,438',
  '233',
  '200,369,120',
  '19,874,369',
  '10,081,785 ',
  'Asia',
  '',
  '94,2920',
  '',
  '',
  '1,378'],
 ['69',
  'Ecuador',
  '1,061,100',
  '',
  '36,019                                ',
  '',
  '1,023,510',
  '',
  '1,571',
  '759',
  '58,581',
  '1,989',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175036',
  '',
  '',
  '87'],
 ['70',
  'Uruguay',
  '1,037,893',
  '',
  '7,625                                ',
  '',
  '1,029,835',
  '',
  '433',
  '18',
  '296,879',
  '2,181',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '',
  '34581',
  '',
  '',
  '124'],
 ['71',
  'Panama',
  '1,037,324',
  '',
  '8,621                                ',
  '',
  '1,028,182',
  '',
  '521',
  '16',
  '233,266',
  '1,939',
  '7,660,443',
  '1,722,623',
  '4,446,964 ',
  'North America',
  '',
  '45161',
  '',
  '',
  '117'],
 ['72',
  'Mongolia',
  '1,007,993',
  '',
  '2,179                                ',
  '',
  '1,005,787',
  '',
  '27',
  '192',
  '298,392',
  '645',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '',
  '31,5501',
  '',
  '',
  '8'],
 ['73',
  'Nepal',
  '1,003,064',
  '',
  '12,031                                ',
  '',
  '990,831',
  '',
  '202',
  '',
  '33,186',
  '398',
  '6,036,615',
  '199,719',
  '30,225,582 ',
  'Asia',
  '',
  '302,5125',
  '',
  '',
  '7'],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800 ',
  'Europe',
  '',
  '91,3251',
  '',
  '',
  '141'],
 ['75',
  'Latvia',
  '977,697',
  '',
  '6,325                                ',
  '',
  '971,095',
  '',
  '277',
  '13',
  '528,817',
  '3,421',
  '7,874,100',
  '4,258,948',
  '1,848,837 ',
  'Europe',
  '',
  '22920',
  '',
  '',
  '150'],
 ['76',
  'Saudi Arabia',
  '841,348',
  '',
  '9,646                                ',
  '',
  '827,696',
  '',
  '4,006',
  '65',
  '23,472',
  '269',
  '45,476,472',
  '1,268,701',
  '35,844,909 ',
  'Asia',
  '',
  '433,7161',
  '',
  '',
  '112'],
 ['77',
  'Azerbaijan',
  '831,460',
  '',
  '10,250                                ',
  '',
  '820,953',
  '',
  '257',

In [5]:
tr_tags = table_code.find_all('tr')
# for i in tr_tags:
#     print(i.text)
tr_tags[0].text.split('\n')

['',
 '#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop',
 '']

In [22]:
# saving scrapped data into csv file
import csv
file = open('covid_Data.csv','w')
x = csv.writer(file)
x.writerows(final_data)

In [21]:
import pandas as pd
df = pd.read_csv('covid_data.csv', on_bad_lines='skip')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1.0,USA,"106,762,797",NaN,"1,162,403",NaN,"104,699,401",NaN,"900,993","1,247",...,"1,178,666,374","3,520,453","334,805,269",North America,NaN,32880,NaN,NaN,"2,691",NaN
1,2.0,India,"44,960,678",NaN,"531,606",NaN,"44,392,828",NaN,"36,244",NaN,...,"927,239,236","659,191","1,406,631,776",Asia,NaN,"312,6462",NaN,NaN,26,NaN
2,3.0,France,"40,007,281",NaN,"166,645",NaN,"39,720,963",NaN,"119,673",869,...,"271,490,188","4,139,547","65,584,518",Europe,NaN,23940,NaN,NaN,"1,825",NaN
3,4.0,Germany,"38,409,620",NaN,"173,307",NaN,"38,204,800",NaN,"31,513",NaN,...,"122,332,384","1,458,359","83,883,596",Europe,NaN,24841,NaN,NaN,376,NaN
4,5.0,Brazil,"37,487,971",NaN,"701,833",NaN,"36,249,161",NaN,"536,977",NaN,...,"63,776,166","296,146","215,353,593",South America,NaN,63073,NaN,NaN,"2,493",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,227.0,Vatican City,29,NaN,,NaN,29,NaN,0,NaN,...,NaN,NaN,799,Europe,NaN,28,NaN,NaN,NaN,NaN
232,228.0,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,NaN,"626,161",Africa,NaN,"62,616626,161",NaN,NaN,NaN,NaN
233,229.0,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,230.0,Tokelau,5,NaN,,NaN,NaN,NaN,5,NaN,...,NaN,NaN,"1,378",Australia/Oceania,NaN,276,NaN,NaN,"3,628",NaN
235,231.0,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,...,"160,000,000","110,461","1,448,471,400",Asia,NaN,"2,878274,7489",NaN,NaN,82,NaN

In [23]:
import pandas as pd
df = pd.read_csv('covid_Data.csv', encoding='latin1')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"106,762,797",NaN,"1,162,403",NaN,"104,699,401",NaN,"900,993","1,247",...,"1,178,666,374","3,520,453","334,805,269",North America,NaN,32880,NaN,NaN,"2,691",NaN
1,2,India,"44,960,678",NaN,"531,606",NaN,"44,392,828",NaN,"36,244",NaN,...,"927,239,236","659,191","1,406,631,776",Asia,NaN,"312,6462",NaN,NaN,26,NaN
2,3,France,"40,007,281",NaN,"166,645",NaN,"39,720,963",NaN,"119,673",869,...,"271,490,188","4,139,547","65,584,518",Europe,NaN,23940,NaN,NaN,"1,825",NaN
3,4,Germany,"38,409,620",NaN,"173,307",NaN,"38,204,800",NaN,"31,513",NaN,...,"122,332,384","1,458,359","83,883,596",Europe,NaN,24841,NaN,NaN,376,NaN
4,5,Brazil,"37,487,971",NaN,"701,833",NaN,"36,249,161",NaN,"536,977",NaN,...,"63,776,166","296,146","215,353,593",South America,NaN,63073,NaN,NaN,"2,493",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Yemen,"11,945",NaN,"2,159",NaN,"9,124",NaN,662,23,...,"329,592","10,579","31,154,867",Asia,NaN,"2,60814,43095",NaN,NaN,21,NaN
196,197,Caribbean Netherlands,"11,682",NaN,38,NaN,"10,476",NaN,"1,168",NaN,...,"30,126","1,130,559","26,647",North America,NaN,27011,NaN,NaN,"43,832",NaN
197,198,Sint Maarten,"11,030",NaN,92,NaN,"10,905",NaN,33,NaN,...,"62,056","1,411,454","43,966",North America,NaN,44781,NaN,NaN,751,NaN
198,199,Eritrea,"10,189",NaN,103,NaN,"10,086",NaN,0,NaN,...,"23,693","6,470","3,662,244",Africa,NaN,"35935,556155",NaN,NaN,NaN,NaN
199,200,Niger,"9,931",NaN,312,NaN,"8,890",NaN,729,1,...,"254,538","9,759","26,083,660",Africa,NaN,"2,62683,601102",NaN,NaN,28,NaN

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 22 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   #                                                     200 non-null    int64
 1   Country,Other                                         200 non-null    object
 2   TotalCases                                            200 non-null    object
 3   NewCases                                              1 non-null      object
 4   TotalDeaths                                           200 non-null    object
 5   NewDeaths                                             1 non-null      float64
 6   TotalRecovered                                        183 non-null    object
 7   NewRecovered                                          6 non-null      object
 8   ActiveCases                                           183 non-null    object
 9   Serious,Critical                                      119 non-null    object
 10  TotÂ Cases/1M pop                                     200 non-null    object
 11  Deaths/1M pop                                         200 non-null    object
 12  TotalTests                                            192 non-null    object
 13  Tests/                                                192 non-null    object
 14  1M pop                                                200 non-null    object
 15  Unnamed: 15                                           200 non-null    object
 16  Population                                            0 non-null      float64
 17  Continent                                             200 non-null    object
 18  1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl  1 non-null      float64
 19  New Cases/1M pop                                      1 non-null      float64
 20  New Deaths/1M pop                                     194 non-null    object
 21  Active Cases/1M pop                                   0 non-null      float64
dtypes: float64(5), int64(1), object(16)
memory usage: 34.5+ KB

In [40]:
# removing comma from the totalcases column and save into list
Country = list(df['Country,Other'][0:5])
TotalCases=list(map(lambda x:int(x.replace(',','')),list(df['TotalCases'][0:5])))
TotalRecovered=list(map(lambda x:int(x.replace(',','')),list(df['TotalRecovered'][0:5])))

In [41]:
import plotly.graph_objects as go

fig = go.Figure([go.Bar(x=Country, y=TotalCases)])
fig.show()

In [42]:
import plotly.graph_objects as go

fig = go.Figure(data=[
    go.Bar(name='TotalCases', x=Country, y=TotalCases),
    go.Bar(name='TotalRecovered', x=Country, y=TotalRecovered)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()